# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

# Ultralytics YOLO11 object detection model with P3/8 - P5/32 outputs
# Model docs: https://docs.ultralytics.com/models/yolo11
# Task docs: https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 4 # number of classes

# YOLO11n backbone
# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 2, CSMB, [256, False, 0.25]]  # 2 <-- MODIFIED from C3k2
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 2, CSMB, [512, False, 0.25]]  # 4 <-- MODIFIED from C3k2
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 2, CSMB, [512, True]]         # 6 <-- MODIFIED from C3k2
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 2, CSMB, [1024, True]]        # 8 <-- MODIFIED from C3k2
  - [-1, 1, LKSP, [1024]]               # 9 <-- MODIFIED from SPPF
  - [-1, 2, C2PSA, [1024]] # 10 (Keeping this attention block)

# YOLO11 head (This example uses your 4-head model)
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 11
  - [[-1, 6], 1, Concat, [1]] # 12
  - [-1, 2, CSMB, [512, False]]              # 13 <-- MODIFIED from C3k2

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 14
  - [[-1, 4], 1, Concat, [1]] # 15
  - [-1, 2, CSMB, [256, False]]              # 16 <-- MODIFIED from C3k2

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 17 (P2 head)
  - [[-1, 2], 1, Concat, [1]] # 18
  - [-1, 2, CSMB, [256, False]]              # 19 <-- MODIFIED from C3k2

  - [-1, 1, Conv, [256, 3, 2]] # 20
  - [[-1, 16], 1, Concat, [1]] # 21
  - [-1, 2, CSMB, [512, False]]              # 22 <-- MODIFIED from C3k2

  - [-1, 1, Conv, [256, 3, 2]] # 23
  - [[-1, 13], 1, Concat, [1]] # 24
  - [-1, 2, CSMB, [512, False]]              # 25 <-- MODIFIED from C3k2

  - [-1, 1, Conv, [512, 3, 2]] # 26
  - [[-1, 10], 1, Concat, [1]] # 27
  - [-1, 2, CSMB, [1024, True]]             # 28 <-- MODIFIED from C3k2

  - [[19, 22, 25, 28], 1, Detect, [nc]] # Detect(P2, P3, P4, P5)